apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: skeleton-scale
spec:
  scaleRef:
    kind: Deployment
    name: skeleton-deployment
    subresource: scale
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization:
    targetPercentage: 75